---
- name: Install Storefront Pre-Reqs
  win_feature:
    name: '{{ item }}'
    state: present
  with_items: '{{ citrix_storefront_prereqs }}'
  register: win_feature

- name: Reboot
  ansible.windows.win_reboot:
  when: win_feature.changed

- name: Create Log Folder
  win_file:
    path: '{{ directory_logging }}'
    state: directory

- name: Print the path
  ansible.builtin.debug:
    msg: '{{ smb_share_path }}'

- name: Create mapped drive with credentials that do not persist on the next logon
  community.windows.win_mapped_drive:
    letter: '{{ smb_share_letter }}'
    path: '\\{{ smb_share_path }}'
    state: present
    username: '{{ smb_share_username }}'
    password: '{{ smb_share_password }}'

- name: Install Storefront Components
  block:
    - win_package:
        path: "{{ citrix_storefront_sources_path }}\\CitrixStoreFront-x64.exe"
        arguments: -silent -noreboot -logpath '{{ directory_logging }}'
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install
  rescue:
    - debug:
          msg: 'Going to reboot and try again'
    - win_reboot:
    - win_package:
        path: "{{ citrix_storefront_sources_path }}\\CitrixStoreFront-x64.exe"
        arguments: /configure_firewall /noreboot /quiet /logpath '{{ directory_logging }}'
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install

- name: Reboot after Storefront
  win_reboot:
  when: sf_install.changed
