---
#- name: Install Storefront Pre-Reqs
#  win_feature:
#    name: '{{ item }}'
#    state: present
#  with_items: '{{ citrix_storefront_prereqs }}'
#  register: win_feature

#- name: Reboot
#  ansible.windows.win_reboot:
#  when: win_feature.changed

- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Debug Output
  ansible.builtin.debug:
    msg: System {{ smb_share }} 

- name: Create mapped drive with credentials that do not persist on the next logon
  community.windows.win_mapped_drive:
    letter: Z
    path: '\\10.10.1.18' # ToDo
    state: present
    username: '{{ smb_share.username }}'
    password: '{{ smb_share.password }}'
  with_items: '{{ smb_share }}'

#- name: Map SMB share
#  win_shell: |
#    net use \\'{{ smb_share.path }}' '{{ smb_share.password }}' /user:'{{ smb_share.user }}'
#  with_items: '{{ smb_share }}'

- name: Install Storefront Components
  block:
    - win_package:
        path: "{{ citrix_storefront_sources_path }}\\CitrixStoreFront-x64.exe"
        arguments: -silent -noreboot -logpath C:\Logs
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install
  rescue:
    - debug:
          msg: 'Going to reboot and try again'
    - win_reboot:
    - win_package:
        path: "{{ citrix_storefront_sources_path }}\\CitrixStoreFront-x64.exe"
        arguments: /configure_firewall /noreboot /quiet /logpath C:\Logs
        state: present
        expected_return_code: [0, 3, 4, 3010]
        creates_path: C:\ProgramData\Citrix\Storefront Install
      register: sf_install

- name: Reboot after Storefront
  win_reboot:
  when: sf_install.changed
